# Generated by Django 6.0.4 on 2026-04-26 16:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono Cliente')),
                ('customer_email', models.CharField(max_length=200, verbose_name='Email Cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('payment_sent', 'Enlace Enviado'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Base Imponible (taxable_amount)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto IVA (vat)')),
                ('tax_percentage', models.IntegerField(choices=[(0, '0%'), (8, '8%'), (15, '15%')], default=15, verbose_name='Porcentaje IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total a Pagar (amount)')),
                ('installments_type', models.IntegerField(choices=[(0, 'Corriente'), (2, 'Con Intereses'), (3, 'Sin Intereses')], default=0, verbose_name='Tipo de Cuotas')),
                ('payment_url', models.URLField(blank=True, verbose_name='URL de Pago')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado Pago')),
                ('nuvei_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Nuvei Transaction ID')),
                ('dev_reference', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Dev Reference')),
                ('ltp_id', models.CharField(blank=True, max_length=100, verbose_name='Link to Pay ID')),
                ('environment', models.CharField(choices=[('STG', 'Staging'), ('PROD', 'Producción')], default='STG', max_length=4, verbose_name='Ambiente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
            },
        ),
    ]
