# Generated by Django 6.0.4 on 2026-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de Autorización'),
        ),
    ]
