# Generated by Django 6.0.4 on 2026-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='webhook_raw_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Webhook Raw Data'),
        ),
    ]
