# Generated by Django 6.0.4 on 2026-04-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Licorería', max_length=200, verbose_name='Nombre de la Tienda')),
                ('environment', models.CharField(choices=[('STG', 'Staging (Desarrollo)'), ('PROD', 'Producción')], default='STG', help_text='Cambia entre Staging (pruebas) y Producción (real).', max_length=4, verbose_name='Ambiente Activo')),
                ('nuvei_app_code_client_stg', models.CharField(default='TEBANSTG-EC-CLIENT', max_length=100, verbose_name='App Code Client (STG)')),
                ('nuvei_app_key_client_stg', models.CharField(blank=True, max_length=200, verbose_name='App Key Client (STG)')),
                ('nuvei_app_code_server_stg', models.CharField(default='TEBANSTG-EC-SERVER', max_length=100, verbose_name='App Code Server (STG)')),
                ('nuvei_app_key_server_stg', models.CharField(blank=True, max_length=200, verbose_name='App Key Server (STG)')),
                ('nuvei_app_code_client_prod', models.CharField(blank=True, max_length=100, verbose_name='App Code Client (PROD)')),
                ('nuvei_app_key_client_prod', models.CharField(blank=True, max_length=200, verbose_name='App Key Client (PROD)')),
                ('nuvei_app_code_server_prod', models.CharField(blank=True, max_length=100, verbose_name='App Code Server (PROD)')),
                ('nuvei_app_key_server_prod', models.CharField(blank=True, max_length=200, verbose_name='App Key Server (PROD)')),
                ('checkout_logo_url', models.URLField(default='https://cdn.paymentez.com/img/nv/nuvei_logo.png', help_text='URL del logo que aparece en el modal de Nuvei Checkout.', verbose_name='Logo Checkout URL')),
                ('checkout_primary_color', models.CharField(default='#C800A1', help_text='Color hexadecimal (ej: #C800A1) para el tema del Checkout.', max_length=7, verbose_name='Color Primario Checkout')),
                ('iva_percentage', models.IntegerField(choices=[(0, '0%'), (8, '8%'), (15, '15%')], default=15, help_text='Tarifa de IVA a aplicar (0%, 8% o 15%).', verbose_name='Porcentaje IVA')),
                ('default_installments_type', models.IntegerField(choices=[(0, 'Corriente'), (2, 'Con Intereses'), (3, 'Sin Intereses')], default=0, verbose_name='Tipo de Cuotas por Defecto')),
                ('whatsapp_number', models.CharField(default='593XXXXXXXXX', help_text='Número con código de país (ej: 593999888777).', max_length=20, verbose_name='Número WhatsApp')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('success_url', models.URLField(blank=True, verbose_name='URL Pago Exitoso')),
                ('failure_url', models.URLField(blank=True, verbose_name='URL Pago Fallido')),
                ('pending_url', models.URLField(blank=True, verbose_name='URL Pago Pendiente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuración de Tienda',
            },
        ),
    ]
