# Generated by Django 6.0.4 on 2026-06-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfig',
            name='nuvei_app_code_client_prod',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='nuvei_app_code_client_stg',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='nuvei_app_key_client_prod',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='nuvei_app_key_client_stg',
        ),
    ]
